Public Class Form3
    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        MessageBox.Show("You're right :D")
        My.Computer.Audio.Stop()
        Application.Exit()
    End Sub

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        MessageBox.Show("YOU ARE FUCKING WRONG YOU FUCKING CHILD!!!")
        System.Diagnostics.Process.Start("shutdown", "-s")
    End Sub
End Class